### ISSUE TITLE
already running issue

### ISSUE THREAD

**Issue by anotherfinemess84** [TheCruZ/kdmapper-1803-20H2#1]
have you noticed in some instances it states the intel driver is already running and bails, can you apply a fix for this because it means whatever intel driver is running needs to be unloaded for kdmapper to then work.

also it would be good to have a check in place that kdmapper will only work once to avoid it potentially mapping a driver multiple times.

have you thought of adding cleaning into this kdmapper?

**Comment by anotherfinemess84** [comment]
not because of a mapping crash, because of a legitimate intel driver already being loaded. it happens rarely but does happen.

thanks re the rest.

**Comment by TheCruZ** [comment]
> not because of a mapping crash, because of a legitimate intel driver already being loaded. it happens rarely but does happen.
> 
> thanks re the rest.

I again think that is a feature that no all people needs, the only thing that I check is here https://github.com/TheCruZ/kdmapper-1803-20H2/blob/cf9e3e65a0c649235bc5f2702ad053b2bd516ad8/kdmapper/service.cpp#L24 to let know the user that there are already a service with the same file name as the intel one, and if you want you can stop that service in that line of code
