### ISSUE TITLE
Potential bug causes the driver to get loaded infinite times!

### ISSUE THREAD

**Issue by Ou7law007** [TheCruZ/kdmapper-1803-20H2#3]
If the execution of the driver takes too long (more than a few seconds), the mapper keeps mapping a new image until the first one returns its status!

Calling KeDelayExecutionThread with Interval about -10000000 (1sec) can sometimes replicate the bug.

Note: It does not always happen, i.e. even if the driver is the exact same, it still doesn't always occur.

**Comment by TheCruZ** [comment]
I have to check this but sound strange as the mapper only calls a patched function in the kernel which will jump to the driver memory (blocking the thread execution of the mapper until ends) and in any case will not try to call this function again

**Comment by Ou7law007** [comment]
I faced this problem a long time ago on both my main machine and my VM. But it never bothered me, since it was rarely occurring.

Now, I'm trying to something a bit different in my driver, where the driver must run for a while (a few minutes or more) that's where the problem arises more and makes my driver way difficult to debug.

After facing it multiple times I can say, there is definitely multiple instances driver being mapped (or at least the entry point is getting called multiple times) concurrently. The output I'm getting in my log.txt file and on my debugger looks something like this:

>At driver entry
>Found 1 at 0x****
>Found 2 at 0x****
>At driver entry
>Found 3 at 0x****
>Found 1 at 0x****
>Found 4 at 0x****
>Found 2 at 0x****
...

That's the minimum. I've faced literal spam of that thing above, even though all instructions above should 100% be executed 1 time (There is no loops, no multithreading going on for sure)

Again, like the title said (Potential), it is still possible that my driver is causing it (for whatever reason)

If you're unable to replicate it at all, contact me I'll take sometime and try to make 100% replicable and then share screen or whatever you like just to make sure it's not my driver that's causing it.

**Comment by TheCruZ** [comment]
Okay now I understand the issue, as I say in the previous comment, the mapper patch (In the last windows versions) NtQueryInformationAtom to call the kernel function from user mode, if you leave your code running and other applications in Windows call this API, will call your driver entry, you can prevent multiple instances running checking for a param or something in your entry point and setting it in the mapper
